version: '3'

services:
  simple-page:
    build: ./simple-page
    env_file: .env
    image: swoldanski/docker-l2p-simple-page:${VERSION:-0.1.5}
    deploy:
      replicas: 3
    labels:
      - "traefik.backend=simple-page"
      - "traefik.frontend.rule=PathPrefixStrip:/,/simple-page"
      - "traefik.backend.loadbalancer.swarm=true"
  
# infra & monitoring
  loadbalancer:
    labels:
      - "traefik.enable=false"
    image: traefik
    command: --web --docker --docker.domain=docker.local --logLevel=DEBUG
    ports:
      - 8080:8080 
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    deploy:
      replicas: 1
    